apiVersion: v1
kind: Service
metadata:
  name: holiday-frontend
spec:
  selector:
    app: holiday-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  # LoadBalancer on Docker Desktop maps EXTERNAL-IP to localhost automatically.
  # Change to ClusterIP + Ingress when moving to AWS EKS.
  type: LoadBalancer
